/** Mixer categories, each with its own volume (GDD 8.5). */
export type SoundCategory = 'ui' | 'phone' | 'ambience' | 'music';

export interface SoundDefinition {
  category: SoundCategory;
  /** File names in assets/sounds/ (without .wav). One is picked at random on each play. */
  variants: readonly string[];
}

/**
 * Every sound the game can play. Volumes live in feel.config.ts.
 * Placeholder files are generated by `npm run sounds:generate`.
 */
export const soundDefinitions = {
  'ui.hover': { category: 'ui', variants: ['ui-hover-1', 'ui-hover-2'] },
  'ui.press': { category: 'ui', variants: ['ui-press-1', 'ui-press-2', 'ui-press-3'] },
  'ui.release': { category: 'ui', variants: ['ui-release-1', 'ui-release-2', 'ui-release-3'] },
  'ui.deny': { category: 'ui', variants: ['ui-deny-1', 'ui-deny-2'] },
  'ui.confirm': { category: 'ui', variants: ['ui-confirm-1'] },
} as const satisfies Record<string, SoundDefinition>;

export type SoundId = keyof typeof soundDefinitions;

export const soundIds = Object.keys(soundDefinitions) as SoundId[];
