/** Mixer categories, each with its own volume (GDD 8.5). */
export type SoundCategory = 'ui' | 'phone' | 'ambience' | 'music';

export interface SoundDefinition {
  category: SoundCategory;
  /** File names in assets/sounds/ (without .wav). One is picked at random on each play. */
  variants: readonly string[];
  /**
   * Played again and again (typing, hovering, turning pages): its volume must stay well below
   * every one-off sound (GDD 6.5). A test enforces it.
   */
  repetitive?: boolean;
}

/**
 * Every sound the game can play. Volumes live in feel.config.ts.
 * Placeholder files are generated by `npm run sounds:generate`.
 */
export const soundDefinitions = {
  'ui.hover': { category: 'ui', variants: ['ui-hover-1', 'ui-hover-2'], repetitive: true },
  'ui.press': { category: 'ui', variants: ['ui-press-1', 'ui-press-2'] },
  'ui.release': { category: 'ui', variants: ['ui-release-1', 'ui-release-2'] },
  'ui.deny': { category: 'ui', variants: ['ui-deny-1', 'ui-deny-2'] },
  'ui.confirm': { category: 'ui', variants: ['ui-confirm-1'] },
  'os.power': { category: 'ui', variants: ['os-power-1'] },
  'os.spinup': { category: 'ambience', variants: ['os-spinup-1'] },
  'os.hdd': { category: 'ambience', variants: ['os-hdd-1', 'os-hdd-2', 'os-hdd-3'] },
  'bios.beep': { category: 'ui', variants: ['bios-beep-1'] },
  'window.open': { category: 'ui', variants: ['window-open-1'] },
  'window.close': { category: 'ui', variants: ['window-close-1'] },
  'window.minimize': { category: 'ui', variants: ['window-minimize-1'] },
  'window.restore': { category: 'ui', variants: ['window-restore-1'] },
  'menu.open': { category: 'ui', variants: ['menu-open-1'] },
  'drag.pick': { category: 'ui', variants: ['drag-pick-1'] },
  'drag.drop': { category: 'ui', variants: ['drag-drop-1'] },
  'page.turn': { category: 'ui', variants: ['page-turn-1', 'page-turn-2'], repetitive: true },
  'viewer.jump': { category: 'ui', variants: ['viewer-jump-1'], repetitive: true },
  'key.press': {
    category: 'ui',
    variants: ['key-1', 'key-2', 'key-3', 'key-4'],
    repetitive: true,
  },
  'clock.skip': { category: 'ambience', variants: ['clock-skip-1'] },
  'phone.ring': { category: 'phone', variants: ['phone-ring-1'] },
  'phone.pickup': { category: 'phone', variants: ['phone-pickup-1'] },
  'phone.hangup': { category: 'phone', variants: ['phone-hangup-1'] },
  'phone.hold': { category: 'phone', variants: ['phone-hold-1'] },
  'chat.receive': { category: 'ui', variants: ['chat-receive-1', 'chat-receive-2'] },
  'chat.send': { category: 'ui', variants: ['chat-send-1'] },
  'capture.mark': { category: 'ui', variants: ['capture-mark-1', 'capture-mark-2'] },
  'option.unlock': { category: 'ui', variants: ['option-unlock-1'] },
  'ticket.stamp': { category: 'ui', variants: ['ticket-stamp-1'] },
  'pen.write': { category: 'ui', variants: ['pen-write-1'] },
} as const satisfies Record<string, SoundDefinition>;

export type SoundId = keyof typeof soundDefinitions;

export const soundIds = Object.keys(soundDefinitions) as SoundId[];
