// Amber cursors on the 32 × 32 grid (GDD 6.4). Compiled to SVG files by
// `npm run cursors:generate`, because CSS cursors must be image files.
import type { PixelArt } from './pixelArt.ts';

export interface CursorArt {
  hotspot: readonly [number, number];
  rows: PixelArt;
}

export const cursorArt = {
  arrow: {
    hotspot: [2, 2],
    rows: [
      '................................',
      '................................',
      '..k.............................',
      '.kAk............................',
      '.kAAk...........................',
      '.kAAAk..........................',
      '.kAAAAk.........................',
      '.kAAAAAk........................',
      '.kAAAAAAk.......................',
      '.kAAAAAAAk......................',
      '.kAAAAAAAAk.....................',
      '.kAAAAAAAAAk....................',
      '.kAAAAAAAAAAk...................',
      '.kAAAAAAAAAAAk..................',
      '.kAAAAAAAAAAAAk.................',
      '.kAAAAAAAAAAAAAk................',
      '.kAAAAAAAAAAAAAAk...............',
      '.kAAAAAAAAAAAAAAAk..............',
      '.kAAAAAAAAAkkkkkk...............',
      '.kAAAAkAAAAAk...................',
      '.kAAAk.kAAAAk...................',
      '.kAAk..kAAAAAk..................',
      '.kAk....kAAAAk..................',
      '..k.....kAAAAAk.................',
      '........kAAAAAk.................',
      '.........kAAAAAk................',
      '.........kAAAAAk................',
      '..........kAkkk.................',
      '...........k....................',
      '................................',
      '................................',
      '................................',
    ],
  },
  denied: {
    hotspot: [2, 2],
    rows: [
      '................................',
      '................................',
      '..k.............................',
      '.kAk............................',
      '.kAAk...........................',
      '.kAAAk..........................',
      '.kAAAAk.........................',
      '.kAAAAAk........................',
      '.kAAAAAAk.......................',
      '.kAAAAAAAk......................',
      '.kAAAAAAAAk.....................',
      '.kAAAAAAAAAk....................',
      '.kAAAAAAAAAAk...................',
      '.kAAAAAAAAAAAk..................',
      '.kAAAAAAAAAAAAk.................',
      '.kAAAAAAAAAAAAAk................',
      '.kAAAAAAAAAAAAAAk...............',
      '.kAAAAAAAAAAAAAAAk...kkkkkk.....',
      '.kAAAAAAAAAkkkkkk..kkkrrrrkkk...',
      '.kAAAAkAAAAAk.....kkrrrrrrrrkk..',
      '.kAAAk.kAAAAk.....krrrrkkrrrrk..',
      '.kAAk..kAAAAAk...kkrrrrkkkkrrkk.',
      '.kAk....kAAAAk...krrrkrrkkkrrrk.',
      '..k.....kAAAAAk..krrkkkrrkkkrrk.',
      '........kAAAAAk..krrkkkkrrkkrrk.',
      '.........kAAAAAk.krrrkkkkrrrrrk.',
      '.........kAAAAAk.kkrrkkkkkrrrkk.',
      '..........kAkkk...krrrrkkrrrrk..',
      '...........k......kkrrrrrrrrkk..',
      '...................kkkrrrrkkk...',
      '.....................kkkkkk.....',
      '................................',
    ],
  },
  hand: {
    hotspot: [11, 2],
    rows: [
      '................................',
      '..........kkkk..................',
      '.........kAAAAk.................',
      '.........kAAAAk.................',
      '.........kAAAAk.................',
      '.........kAAAAk.................',
      '.........kAAAAk.................',
      '.........kAAAAk.................',
      '.........kAAAAkkkk..............',
      '.........kAAAAAAAAkkkk..........',
      '.........kAAAAAAAAAAAAkkk.......',
      '.........kAAAAkAAAAAAAAAAk......',
      '.........kAAAAkAAAkAAAAAAk......',
      '....kk...kAAAAkAAAkAAAkAAk......',
      '...kAAkkkkAAAAkAAAkAAAkAAk......',
      '..kAAAAAAAAAAAkAAAkAAAkAAk......',
      '...kAAAAAAAAAAAAAAkAAAkAAk......',
      '....kAAAAAAAAAAAAAAAAAkAAk......',
      '....kAAAAAAAAAAAAAAAAAAAAk......',
      '.....kAAAAAAAAAAAAAAAAAAAk......',
      '......kAAAAAAAAAAAAAAAAAAk......',
      '......kAAAAAAAAAAAAAAAAAAk......',
      '......kAAAAAAAAAAAAAAAAAAk......',
      '......kAAAAAAAAAAAAAAAAAAk......',
      '......kAAAAAAAAAAAAAAAAAAk......',
      '.......kkAAAAAAAAAAAAAAkk.......',
      '........kAAAAAAAAAAAAAAk........',
      '........kAAAAAAAAAAAAAAk........',
      '........kAAAAAAAAAAAAAAk........',
      '.........kkkkkkkkkkkkkk.........',
      '................................',
      '................................',
    ],
  },
  text: {
    hotspot: [16, 16],
    rows: [
      '................................',
      '................................',
      '...........kkkk..kkkk...........',
      '..........kAAAAkkAAAAk..........',
      '..........kAAAAkkAAAAk..........',
      '...........kkkkAAkkkk...........',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '..............kAAk..............',
      '...........kkkkAAkkkk...........',
      '..........kAAAAkkAAAAk..........',
      '..........kAAAAkkAAAAk..........',
      '...........kkkk..kkkk...........',
      '................................',
      '................................',
    ],
  },
  wait: {
    hotspot: [16, 16],
    rows: [
      '................................',
      '................................',
      '.......kkkkkkkkkkkkkkkkkk.......',
      '......kVVVVVVVVVVVVVVVVVVk......',
      '......kVVVVVVVVVVVVVVVVVVk......',
      '......kvvvvvvvvvvvvvvvvvvk......',
      '.......kkbbbbbbbbbbbbbbkk.......',
      '.........kbbbbbbbbbbbbk.........',
      '.........kbbbbbbbbbbbk..........',
      '..........kAAAAAAAAAAk..........',
      '...........kAAAAAAAAk...........',
      '...........kbAAAAAAbk...........',
      '............kbAAAAbk............',
      '............kbAAAAk.............',
      '.............kbbbbk.............',
      '..............kAAk..............',
      '..............kAAk..............',
      '.............kbAAbk.............',
      '............kbbAAbk.............',
      '............kbbAAbbk............',
      '...........kbbbAAbbbk...........',
      '...........kbbAAAbbbk...........',
      '..........kbbAAAAAbbbk..........',
      '.........kbbAAAAAAAbbk..........',
      '.........kbAAAAAAAAAbbk.........',
      '.......kkbAAAAAAAAAAAbbkk.......',
      '......kVVVVVVVVVVVVVVVVVVk......',
      '......kVVVVVVVVVVVVVVVVVVk......',
      '......kvvvvvvvvvvvvvvvvvvk......',
      '.......kkkkkkkkkkkkkkkkkk.......',
      '................................',
      '................................',
    ],
  },
} as const satisfies Record<string, CursorArt>;

export type CursorName = keyof typeof cursorArt;
