/**
 * Compiles the pixel-art cursors (src/ui/icons/cursorArt.ts) into SVG files in assets/cursors/,
 * and writes src/ui/theme/cursors.css with one CSS variable per cursor (hotspot included).
 * Usage: npm run cursors:generate
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cursorArt } from '../src/ui/icons/cursorArt.ts';
import { PIXEL_GRID, toRuns } from '../src/ui/icons/pixelArt.ts';
import { palette } from '../src/ui/theme/palette.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'assets', 'cursors');
const CSS_FILE = join(ROOT, 'src', 'ui', 'theme', 'cursors.css');

/** Native cursor used if the SVG cannot be loaded. */
const fallbacks: Record<keyof typeof cursorArt, string> = {
  arrow: 'default',
  denied: 'not-allowed',
  hand: 'pointer',
  text: 'text',
  wait: 'wait',
};

mkdirSync(OUT_DIR, { recursive: true });
const cssLines: string[] = [
  '/* Generated by tools/generate-cursors.ts — do not edit, edit src/ui/icons/cursorArt.ts. */',
  ':root {',
];

for (const [name, cursor] of Object.entries(cursorArt) as [
  keyof typeof cursorArt,
  (typeof cursorArt)[keyof typeof cursorArt],
][]) {
  const rects = toRuns(cursor.rows)
    .map(
      (r) =>
        `<rect x="${r.x}" y="${r.y}" width="${r.width}" height="1" fill="${palette[r.color]}"/>`,
    )
    .join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${PIXEL_GRID}" height="${PIXEL_GRID}" viewBox="0 0 ${PIXEL_GRID} ${PIXEL_GRID}" shape-rendering="crispEdges">${rects}</svg>\n`;
  writeFileSync(join(OUT_DIR, `${name}.svg`), svg);
  const [hx, hy] = cursor.hotspot;
  cssLines.push(
    `  --cursor-${name}: url('../../../assets/cursors/${name}.svg') ${hx} ${hy}, ${fallbacks[name]};`,
  );
  console.log(`wrote ${name}.svg`);
}

cssLines.push('}', '');
writeFileSync(CSS_FILE, cssLines.join('\n'));
console.log(`wrote ${CSS_FILE}`);
