/** Pure renderers for the generated theme files (used by generate-theme.ts and by the tests). */
import { cursorArt, type CursorName } from '../src/ui/icons/cursorArt.ts';
import { PIXEL_GRID, toRuns } from '../src/ui/icons/pixelArt.ts';
import {
  DEFAULT_PALETTE,
  paletteCssVar,
  paletteNames,
  paletteRoles,
  palettes,
  type PaletteName,
} from '../src/ui/theme/palette.ts';

const HEADER =
  '/* Generated by tools/generate-theme.ts from palette.ts / cursorArt.ts — do not edit. */';

/** Native cursor used if the SVG cannot be loaded. */
const fallbacks: Record<CursorName, string> = {
  arrow: 'default',
  denied: 'not-allowed',
  hand: 'pointer',
  text: 'text',
  wait: 'wait',
};

export const cursorNames = Object.keys(cursorArt) as CursorName[];

/** The default palette also applies to a bare :root (before any data-palette is set). */
function selector(name: PaletteName): string {
  const scoped = `:root[data-palette='${name}']`;
  return name === DEFAULT_PALETTE ? `:root,\n${scoped}` : scoped;
}

export function renderPalettesCss(): string {
  const blocks = paletteNames.map((name) => {
    const lines = paletteRoles.map((role) => `  ${paletteCssVar(role)}: ${palettes[name][role]};`);
    return `${selector(name)} {\n${lines.join('\n')}\n}`;
  });
  return `${HEADER}\n${blocks.join('\n\n')}\n`;
}

export function cursorFile(palette: PaletteName, cursor: CursorName): string {
  return `${palette}/${cursor}.svg`;
}

export function renderCursorSvg(palette: PaletteName, cursor: CursorName): string {
  const rects = toRuns(cursorArt[cursor].rows)
    .map(
      (r) =>
        `<rect x="${r.x}" y="${r.y}" width="${r.width}" height="1" fill="${palettes[palette][r.color]}"/>`,
    )
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${PIXEL_GRID}" height="${PIXEL_GRID}" viewBox="0 0 ${PIXEL_GRID} ${PIXEL_GRID}" shape-rendering="crispEdges">${rects}</svg>\n`;
}

export function renderCursorsCss(): string {
  const blocks = paletteNames.map((name) => {
    const lines = cursorNames.map((cursor) => {
      const [x, y] = cursorArt[cursor].hotspot;
      const url = `../../../assets/cursors/${cursorFile(name, cursor)}`;
      return `  --cursor-${cursor}: url('${url}') ${x} ${y}, ${fallbacks[cursor]};`;
    });
    return `${selector(name)} {\n${lines.join('\n')}\n}`;
  });
  return `${HEADER}\n${blocks.join('\n\n')}\n`;
}
