/** Pure renderers for the generated theme files (used by generate-theme.ts and by the tests). */
import { cursorArt, type CursorName } from '../src/ui/icons/cursorArt.ts';
import { PIXEL_GRID, toRuns } from '../src/ui/icons/pixelArt.ts';
import { palette, paletteCssVar, paletteRoles } from '../src/ui/theme/palette.ts';

const HEADER =
  '/* Generated by tools/generate-theme.ts from palette.ts / cursorArt.ts — do not edit. */';

/** Native cursor used if the SVG cannot be loaded. */
const fallbacks: Record<CursorName, string> = {
  arrow: 'default',
  denied: 'not-allowed',
  hand: 'pointer',
  text: 'text',
  wait: 'wait',
  'resize-ns': 'ns-resize',
  'resize-ew': 'ew-resize',
  'resize-nwse': 'nwse-resize',
  'resize-nesw': 'nesw-resize',
};

export const cursorNames = Object.keys(cursorArt) as CursorName[];

export function renderPaletteCss(): string {
  const lines = paletteRoles.map((role) => `  ${paletteCssVar(role)}: ${palette[role]};`);
  return `${HEADER}\n:root {\n${lines.join('\n')}\n}\n`;
}

export function cursorFile(cursor: CursorName): string {
  return `${cursor}.svg`;
}

export function renderCursorSvg(cursor: CursorName): string {
  const rects = toRuns(cursorArt[cursor].rows)
    .map(
      (r) =>
        `<rect x="${r.x}" y="${r.y}" width="${r.width}" height="1" fill="${palette[r.color]}"/>`,
    )
    .join('');
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${PIXEL_GRID}" height="${PIXEL_GRID}" viewBox="0 0 ${PIXEL_GRID} ${PIXEL_GRID}" shape-rendering="crispEdges">${rects}</svg>\n`;
}

export function renderCursorsCss(): string {
  const lines = cursorNames.map((cursor) => {
    const [x, y] = cursorArt[cursor].hotspot;
    const url = `../../../assets/cursors/${cursorFile(cursor)}`;
    return `  --cursor-${cursor}: url('${url}') ${x} ${y}, ${fallbacks[cursor]};`;
  });
  return `${HEADER}\n:root {\n${lines.join('\n')}\n}\n`;
}
